name: actions
on:
  push:
    branches: [ primary, updates, testing ]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build containers
        run: docker-compose build
      - name: Run tests
        run: |
          docker-compose run -itd web sh
          bin/rails test
