name: actions
on:
  push:
    branches: [ primary, updates, testing ]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Start containers
        run: docker-compose up -d
      - name: Run tests
        run: |
        docker-compose exec web bin/rails test
      - name: Stop containers
        if: always()
        run: docker-compose down
